# Generated by Django 2.2 on 2019-12-16 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='image_list',
        ),
    ]
